### ISSUE TITLE
When updating I get reachedTimeLimit error

### ISSUE THREAD

**Issue by johandk89** [JanGorman/Table#1]
I added https://github.com/JanGorman/Table.git to my `Package.swift` file but when running `swift package update` I get this error: 
```
error: reachedTimeLimit
```

**Comment by JanGorman** [comment]
I didn't create a release tag 🤦‍♂️. Just did it now, could you try again pls.

**Comment by johandk89** [comment]
Great! Its working now 👍
And thanks for the quick response

**Comment by johandk89** [comment]
It seems like the Framework is not created and added to the Xcode project. Here is my package.swift file: 
``` 
import PackageDescription
let package = Package(
  name: "gitlab",
  dependencies: [
    .Package(url: "https://github.com/oarrabi/Guaka.git", majorVersion: 0),
    .Package(url: "https://github.com/Alamofire/Alamofire.git", majorVersion: 4),
    .Package(url: "https://github.com/JohnSundell/ShellOut.git", majorVersion: 2),
    .Package(url: "https://github.com/Swiftline/Swiftline.git", majorVersion: 0, minor: 5),
    .Package(url: "https://github.com/SwiftyJSON/SwiftyJSON.git", majorVersion: 4),
    .Package(url: "https://github.com/JanGorman/Table.git", majorVersion: 1)
    ]
)
```

And here is the list of frameworks generated: 
![screen shot 2017-11-30 at 08 49 53](https://user-images.githubusercontent.com/1677887/33417757-734f17f2-d5ab-11e7-9268-77e92c521dec.png)

**Comment by JanGorman** [comment]
Bizarre, need to try this

**Comment by JanGorman** [comment]
Got it, the Package.swift was missing a product definition. https://github.com/JanGorman/Table/commit/78c04b58a006a48f5ccf2fdda563d021f2c54747 fixes it. Heads up: Looking at your Package.swift, looks like it's using the Swift 3 format though?

**Comment by JanGorman** [comment]
Did the 1.0.1 fix the issue you were experiencing?

**Comment by johandk89** [comment]
Yes it did, thanks
